### PR TITLE
fix(*): remove comments and last traces of cookoo

### LINKED ISSUE #330: Remove Godoc comments that mention "cookoo"
# Summary

After #316 is done, cookoo will be removed, but there are still some Godoc comments that mention it. They should be removed and/or refactored to make sense in a non-cookoo world.

# Related Issues

Cookoo is removed in #316, so this issue is necessarily dependent upon that PR

### PR DESCRIPTION
**Pull request by arschles**
# Summary of Changes

#316 removed almost all of [cookoo](https://github.com/Masterminds/cookoo) related code and comments that mention cookoo, and this patch removes the remaining bits and pieces of code, dependencies and documentation that mention it.

Credit @smothiki for doing the _real_ work to remove cookoo in #316 

# Issue(s) that this PR Closes

Closes #330

# Pull Request Hygiene TODOs

Please make sure the below checklist is complete.

- [x] Your pull request is concise and to the point (make another PR for refactoring nearby code)
- [x] Your commits follow the [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)

### CODE REVIEW

**Comment by bacongobbler** [comment]
so long, cookoo

**Comment by kmala** [comment]
you had changed the glide commits tags of others also.....is that intended because the build is failing

**Comment by arschles** [comment]
@kmala yea, it's a casualty of running a `glide up` in an attempt to remove cookoo from the `glide.lock` file. I'm going to add those deps to the `glide.yaml` and pin them to their old SHAs.

**Comment by arschles** [comment]
@kmala fixed in https://github.com/deis/builder/pull/346/commits/8e301f559dd5c61b0d76e3909003efef97eca66c

**Pull request merged**
