### PR TITLE
Fix ObjectStorageTickDurationMSec envconfig typo

### PR DESCRIPTION
**Pull request by kwent**
### Fix ObjectStorageTickDurationMSec envconfig typo

`envconfing` to `envconfig`

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
Nice catch. This has been there [for over a year now](https://github.com/deis/builder/commit/b4f79d31a6239c46fe70e834c9d3197a9fc5238b)! Guess nobody else was using this feature.

LGTM

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by mboersma** [comment]
@kwent, could you `git amend` this commit to match our [style guide](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#commit-style)? Then it will be included in the CHANGELOG. Something like:
```
fix(gitreceive/config.go): correct envconfig typo
```

**Comment by kwent** [comment]
@mboersma Done !

**Pull request merged**
