### PR TITLE
feat(builder): adjust dockerbuilder and slugrunner templates

### PR DESCRIPTION
**Pull request by smothiki**
Modify dockerbuilder and slugbuilder templates if the secret is not present.

### CODE REVIEW

**Comment by arschles** [comment]
@smothiki do we want to support running object storage without auth? IMO the answer is no, do you have a use case?

**Comment by smothiki** [comment]
For fetcher which runs with out auth for now. Also if we want to give customizable storage solutions or outside storage which doesn't have auth then this will be helpful

**Comment by arschles** [comment]
> For fetcher which runs with out auth for now

We agreed that Fetcher is gonna go away (#6)

>Also if we want to give customizable storage solutions or outside storage which doesn't have auth then this will be helpful

IMO we shouldn't encourage anyone to run object storage (especially not outside storage, but also in-cluster storage) without auth

**Comment by smothiki** [comment]
In this PR I'm just fixing secrets as we have changed from object-store to minio-user. If we are thinking enforcing auth strictly I'll create different PR

**Comment by arschles** [comment]
Ok, makes sense. I assumed wrong about what this PR was going to be. Sorry for jumping the gun, and let me know when you're ready for a review.

**Comment by smothiki** [comment]
I have tested it and commands are working this PR ready for a review

**Pull request merged**
