### PR TITLE
fix(pkg): rename workflow to controller

### PR DESCRIPTION
**Pull request by bacongobbler**
this broke with the change in https://github.com/deis/charts/pull/153

### CODE REVIEW

**Comment by bacongobbler** [comment]
pinging @smothiki @arschles -- do you know of any spots in dockerbuilder/slugbuilder that require information from the API server?

**Comment by smothiki** [comment]
You have to make changes in builder . Not required in any build pods

**Comment by smothiki** [comment]
https://github.com/deis/builder/blob/master/pkg/gitreceive/config.go
also lot other places

**Comment by bacongobbler** [comment]
that's been changed in this PR :)

**Comment by smothiki** [comment]
Oops my apologies

**Comment by smothiki** [comment]
Did you manually test this ?

**Comment by bacongobbler** [comment]
I have not.

**Comment by smothiki** [comment]
Also these https://github.com/deis/builder/search?utf8=%E2%9C%93&q=workflow are not critical but helps if you can include them in this PR

**Comment by bacongobbler** [comment]
here is the current environment in the latest charts:

```
><> kd exec deis-builder-3y1mw env | grep CONTROLLER
DEIS_CONTROLLER_PORT_80_TCP_PROTO=tcp
DEIS_CONTROLLER_PORT_80_TCP_PORT=80
DEIS_CONTROLLER_SERVICE_HOST=10.247.235.46
DEIS_CONTROLLER_SERVICE_PORT=80
DEIS_CONTROLLER_PORT=tcp://10.247.235.46:80
DEIS_CONTROLLER_PORT_80_TCP_ADDR=10.247.235.46
DEIS_CONTROLLER_SERVICE_PORT_HTTP=80
DEIS_CONTROLLER_PORT_80_TCP=tcp://10.247.235.46:80
```

> Also these https://github.com/deis/builder/search?utf8=%E2%9C%93&q=workflow are not critical but helps if you can include them in this PR

Absolutely. I'll update that :)

**Comment by arschles** [comment]
@bacongobbler code LGTM. I'll label as such, but post some testing instructions and I'll test if you want

**Comment by bacongobbler** [comment]
Tesing:

What you should see on master because the builder cannot communicate with the controller:

```
><> git push deis master
The authenticity of host '[deis.10.245.1.3.xip.io]:2222 ([10.245.1.3]:2222)' can't be established.
ECDSA key fingerprint is eb:b6:ec:eb:a3:83:d1:b9:ef:26:c1:fc:a8:83:3f:4d.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[deis.10.245.1.3.xip.io]:2222,[10.245.1.3]:2222' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

A deployment with this change should work again.

**Comment by arschles** [comment]
@bacongobbler :heavy_check_mark:

**Pull request merged**
