### PR TITLE
ref(ssh keys): remove support for DSA

### PR DESCRIPTION
**Pull request by vdice**
Ref https://github.com/golang/go/issues/19424

A ~~potential~~ fix/solution for https://github.com/deis/builder/issues/462 ~~(need further testing/deployment into clusters to be sure)~~

### CODE REVIEW

**Comment by vdice** [comment]
This has been running on a personal GKE cluster since this morning and panic described in https://github.com/deis/builder/issues/462 has not been encountered; we've recently deployed to our dogfood cluster as well.  Aside from the user ramifications (looking for community/user feedback on that detail), this may be a path forward...

**Comment by Bregor** [comment]
Is there any instructions on how to build/install?

**Comment by vdice** [comment]
>Is there any instructions on how to build/install?

Good question, apologies for not mentioning.  For others who would like to apply patch, simply `kubectl -n deis edit deploy deis-builder` and swap in `quay.io/deisci/builder:git-e0765bf` for the image.

**Comment by Bregor** [comment]
Also you can use `set` instead of `edit`:

    $ kubectl -n deis set image deployment deis-builder deis-builder=quay.io/deisci/builder:git-e0765bf

**Comment by vdice** [comment]
Closes https://github.com/deis/builder/issues/462

**Comment by Bregor** [comment]
$ kubectl get po -n deis | head -2
    NAME                                     READY     STATUS    RESTARTS   AGE
    deis-builder-1727066652-mhq1s            1/1       Running   0          2d

It's a miracle!
;)

**Comment by bacongobbler** [comment]
I'm all for this if it fixes things. LGTM.

**Comment by mboersma** [comment]
I think removing the DSA key support is a small price to pay for fixing this pernicious bug.

**Pull request merged**
