### PR TITLE
fix(*): add godocs and address other golint issues

### LINKED ISSUE #230: Fix golint issues
There are [currently a lot](https://goreportcard.com/report/github.com/deis/builder#golint), many around lack of documentation. Not all of these need to be fixed, but more docs should be added.

### PR DESCRIPTION
**Pull request by arschles**
Also:

- Ensure that comments (including godoc comments, but _not_ code) don't expand beyond the 99 character limit described in the [code standards](http://docs.deis.io/en/latest/contributing/standards/#code-standards)
- Fix some small grammatical issues in docs
- Ensure that all godoc documentation is written with complete sentences

Fixes #230

### CODE REVIEW

**Comment by mboersma** [comment]
Awesome! Two minor comments:
- Our [code standards](http://docs.deis.io/en/latest/contributing/standards/#code-standards) limit Go code width to 99 chars, but some of these doc comments look longer.
- [Effective Go](https://golang.org/doc/effective_go.html#commentary) recommends complete sentences, so these doc comments should end with periods like in Go's stdlib.

**Comment by arschles** [comment]
@mboersma thanks for the comments!

I'll modify this code to adhere to the 99 character limit, and I'll also ensure that we have complete sentences, with punctuation, in our docs. Commits forthcoming.

**Comment by arschles** [comment]
@mboersma 4b534587f96cf9b8e7b79a110f288520485a8819 and 3aa2eb408e7a889b67ac56312450da8de417290b limit comment lines (godoc and otherwise) to 99 chars and ensure that sentences are properly terminated.

Also, sidenote: I've created #251 to capture the work for writing package-level godocs. I'm considering that out of scope of this PR.

**Comment by mboersma** [comment]
There were already a lot of good documentation comments in here, and this improves many of them and fills in gaps where they were missing. This is excellent-I re-read this whole PR and I feel like I have a better understanding of builder just from that. :+1:

**Comment by arschles** [comment]
thanks @mboersma 

fwiw, things will get even clearer after https://github.com/deis/builder/issues/152 is done, but I digress.... :see_no_evil:

**Comment by arschles** [comment]
Merged as part of `v2.0-beta1`, since I believe this will help new contributors to get started on the codebase

**Pull request merged**
