### PR TITLE
ref(git-receive): refactor cookoo out of the git receive func

### PR DESCRIPTION
**Pull request by arschles**
Ref #152 

~~This PR is a work in progress because tests still fail.~~ Tests have been fixed

### CODE REVIEW

**Comment by mboersma** [comment]
@arschles is this still a work-in-progress? It looks like a good refactoring to me, although needs rebasing.

**Comment by arschles** [comment]
@mboersma I was actually waiting for e2e to succeed, but now that it has, I'll remove the `WIP` from the title. After I rebase I'll ask again for another review. Thanks!

**Comment by mboersma** [comment]
@arschles could you rebase this so we can resolve it?

**Comment by arschles** [comment]
@mboersma this is obsoleted by https://github.com/deis/builder/pull/316, so I'll close when that's merged

**Comment by arschles** [comment]
@smothiki I'd like to close this now in favor of #316, in anticipation of that PR's merge. Reasonable to you?

**Comment by arschles** [comment]
Closing in favor of #316 after offline discussion with @smothiki

**Pull request closed without merging**
