### PR TITLE
fix(Makefile,build.go,build_type.go,build_type_test.go): choose slug builds by default, unless a Dockerfile is present

### LINKED ISSUE #124: Defaults to docker build if no Procfile found?
I believe the README is incorrect:

> If a Dockerfile is present, starts a dockerbuilder pod, configured to download the code to build from the > URL computed in the previous step (dockerbuilder and Dockerfile builder are not currently supported. > See https://github.com/deis/dockerbuilder/pull/1 for prototype dockerbuilder code).
> 
> Otherwise, starts a slugbuilder pod, configured to download the code to build from the URL computed in the previous step.

It seems like the current code *defaults* to dockerbuilder and will only use slugbuilder if a Procfile is found. This is a different behaviour from deis v1 which defaulted to slugbuilder and only used dockerbuilder if a Dockerfile was found.

https://github.com/deis/builder/blob/439d2e9033877e380b70ad53eaf0bdd8da26a104/pkg/gitreceive/build.go#L126

### PR DESCRIPTION
**Pull request by arschles**
Fixes #124

cc/ @olalonde

### CODE REVIEW

**Comment by aledbf** [comment]
Code LGTM.

```
$ cat Dockerfile
FROM SCRATCH

CMD ["true"]

$ cat Procfile
web: true
```

create app and push
```
git add Dockerfile Procfile
git commit -m 'Initial import'
git push deis master
deis-v2 create issue124
```

```
$ git push deis master
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (4/4), 300 bytes | 0 bytes/s, done.
Total 4 (delta 0), reused 0 (delta 0)
Running in debug mode
Running git hook
read [0000000000000000000000000000000000000000,afee415a77b5032c94555a3deef3a4d72fc5e675,refs/heads/master]
Workflow request /v2/hooks/push (body elided)
Workflow request POST /v2/hooks/config
{"receive_user":"alejandro.debrito","receive_repo":"issue124"}
got the following config back for app issue124: {Owner:alejandro.debrito App:issue124 Values:map[] Memory:map[] CPU:map[] Tags:map[] UUID:afc70872-de58-4ce3-b692-ad84e2039509 Created:2016-01-25 21:58:49 +0000 UTC Updated:2016-01-25 21:58:49 +0000 UTC}
running [git archive --format=tar.gz --output=issue124.tar.gz afee415a77b5032c94555a3deef3a4d72fc5e675] in directory /home/git/issue124.git
running [tar -xzf issue124.tar.gz -C /tmp/] in directory /home/git/issue124.git
writing builder manifest to /etc/issue124:git-afee415a
running [mc -C /var/minio-conf --quiet config host add http://10.3.3.23:9000 8TZRY2JRWMPT6UMXR6I5 gbstrOvotMMcg2sMfGUhA5a6Et/EI5ALtIHsobYk]
running [mc -C /var/minio-conf --quiet mb http://10.3.3.23:9000/git]
running [mc -C /var/minio-conf --quiet cp issue124.tar.gz http://10.3.3.23:9000/git/home/issue124:git-afee415a/tar] in directory /home/git/issue124.git
-----> Starting build... but first, coffee!
Starting pod dockerbuild-issue124-afee415a-1371d317
...
```

```
git delete Dockerfile
git rm Dockerfile
git commit -m "only procfile"
git push deis master
```

```
$ git push deis master
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (6/6), 511 bytes | 0 bytes/s, done.
Total 6 (delta 0), reused 0 (delta 0)
Running in debug mode
Running git hook
read [0000000000000000000000000000000000000000,75aeeee1695a35d785a49204474158e7eaf5890d,refs/heads/master]
Workflow request /v2/hooks/push (body elided)
Workflow request POST /v2/hooks/config
{"receive_user":"alejandro.debrito","receive_repo":"issue124"}
got the following config back for app issue124: {Owner:alejandro.debrito App:issue124 Values:map[] Memory:map[] CPU:map[] Tags:map[] UUID:afc70872-de58-4ce3-b692-ad84e2039509 Created:2016-01-25 21:58:49 +0000 UTC Updated:2016-01-25 21:58:49 +0000 UTC}
running [git archive --format=tar.gz --output=issue124.tar.gz 75aeeee1695a35d785a49204474158e7eaf5890d] in directory /home/git/issue124.git
running [tar -xzf issue124.tar.gz -C /tmp/] in directory /home/git/issue124.git
writing builder manifest to /etc/issue124:git-75aeeee1
running [mc -C /var/minio-conf --quiet config host add http://10.3.3.23:9000 8TZRY2JRWMPT6UMXR6I5 gbstrOvotMMcg2sMfGUhA5a6Et/EI5ALtIHsobYk]
running [mc -C /var/minio-conf --quiet mb http://10.3.3.23:9000/git]
running [mc -C /var/minio-conf --quiet cp issue124.tar.gz http://10.3.3.23:9000/git/home/issue124:git-75aeeee1/tar] in directory /home/git/issue124.git
-----> Starting build... but first, coffee!
Starting pod slugbuild-issue124-75aeeee1-1852460d
running [kubectl --namespace=deis create -f /etc/issue124:git-75aeeee1]
...
```


@arschles only one small comment, [here](https://github.com/arschles/builder/blob/build-choice/pkg/gitreceive/build.go#L141) is not clear where err comes from

**Comment by arschles** [comment]
ah, thanks @aledbf - that's an untested codepath to handle systems with object storage systems with no authentication turned on. That line should actually be `if creds == nil`. Changing now

**Comment by arschles** [comment]
@aledbf fix made in https://github.com/arschles/builder/commit/469df267e09cc86ba433a2e63c3ed36ff988c85e

**Comment by aledbf** [comment]
>  That line should actually be if creds == nil

yes, now is clear :+1:

**Comment by aledbf** [comment]
@arschles  about the error: `code.google.com/p/go-uuid/uuid` is now located in `https://github.com/pborman/uuid`

**Comment by arschles** [comment]
@aledbf looks like there are quite a few warnings on pulling packages from `code.google.com`. For example, https://travis-ci.org/deis/builder/builds/104773570#L206. Investigating...

**Comment by arschles** [comment]
@aledbf FYI I've changed the explicit import to `https://github.com/pborman/uuid` for now, and it fixed the build. May need to migrate more dependencies from `code.google.com` in the future

**Comment by olalonde** [comment]
@arschles thanks :+1:

**Comment by aledbf** [comment]
@arschles [this]( https://news.ycombinator.com/item?id=10972561) is the real problem with `code.google.com`

**Comment by arschles** [comment]
Ah, thanks @aledbf . I'll move us over to equivalent github based packages as necessary.

**Pull request merged**
