### PR TITLE
RBAC support

### PR DESCRIPTION
**Pull request by Bregor**
With this change deis-builder became available to work in **RBAC**-only clusters

Works with both Kubernetes 1.5 and 1.6 (see `templates/_helpers.tmpl` for details)
Actually tested with 1.5.7 and 1.6.2

Role allows `deis-builder`:
- `secrets`: `create`, `update` and `delete`
- `pods`: `get`, `list`, `watch` and `create`
- `pods/log:` `get`

ClusterRole allows `deis-builder`:
- `namespaces`: `list`

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by vdice** [comment]
Jenkins, OK to test

**Comment by vdice** [comment]
Jenkins, add to whitelist

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Pull request merged**
