### PR TITLE
fix(Makefile,glide.lock): upgrade to glide 0.8 & add lockfile

### LINKED ISSUE #70: upgrade to glide 0.8+
- Use the `quay.io/deis/go-dev:0.3.0` or higher image to get glide 0.8+
- Use `glide install` in the `bootstrap` build target in the makefile
- Check in the `glide.lock` file to match appropriate versions of each dependency to build this codebase

### PR DESCRIPTION
**Pull request by arschles**
Fixes #70

### CODE REVIEW

**Comment by slack** [comment]
Have you tested builder with this glide change?

**Comment by arschles** [comment]
no, but I just added the appropriate label and will do so for sure before merging

**Comment by arschles** [comment]
@slack tested `git push` from nothing against builder with this change and all other stock components. Looks like we're good to go. See output below:

```console
ENG000656:example-go aaronschlesinger$ deis register deis.108.59.84.244.xip.io
username: arschles
password: 
password (confirm): 
email: arschles@gmail.com
Registered arschles
Logged in as arschles
ENG000656:example-go aaronschlesinger$ deis keys:add ~/.ssh/id_rsa.pub 
Uploading id_rsa.pub to deis... done
ENG000656:example-go aaronschlesinger$ deis create gotest
Creating Application... done, created gotest
Git remote deis added
remote available at ssh://git@deis.108.59.84.244.xip.io:2222/gotest.git
ENG000656:example-go aaronschlesinger$ git push deis master
The authenticity of host '[deis.108.59.84.244.xip.io]:2222 ([108.59.84.244]:2222)' can't be established.
ECDSA key fingerprint is SHA256:dz2YDHEz6oEWPJcjmIhqPIs5qWXlSnN0sDjkusSHkUs.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[deis.108.59.84.244.xip.io]:2222,[108.59.84.244]:2222' (ECDSA) to the list of known hosts.
Counting objects: 270, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (125/125), done.
Writing objects: 100% (270/270), 3.02 MiB | 602.00 KiB/s, done.
Total 270 (delta 148), reused 241 (delta 131)
-----> Starting build
-----> Go app detected
-----> Checking Godeps/Godeps.json file.
-----> Installing go1.4.2... done
-----> Running: godep go install -tags heroku ./...
-----> Discovering process types
       Procfile declares types -> web
-----> Compiled slug size is 4.7M
-----> Build complete.
-----> Launching app.
-----> Launching... 
       done, gotest:v2 deployed to Deis

       http://gotest.localhost

       To learn more, use `deis help` or visit http://deis.io

To ssh://git@deis.108.59.84.244.xip.io:2222/gotest.git
 * [new branch]      master -> master
ENG000656:example-go aaronschlesinger$ curl gotest.108.59.84.244.xip.io
Powered by Deis
Release v2 on gotest-v2-web-v1un0
```

**Comment by technosophos** [comment]
Manually tested and verified that 0.3 image is pulled and that the glide.lock is appropriately reconstituted, and that the resulting build is valid.

**Comment by arschles** [comment]
thanks @technosophos

**Pull request merged**
