### PR TITLE
fix(pkg/git/git.go): write the pre-receive hook script directly to the file descriptor

### LINKED ISSUE #321: change createPreReceiveHook to use execute the template directly to the file
# Summary

the `createPreReceiveHook` func (in `pkg/git/git.go`) renders a template to a `bytes.Buffer`, then calls `ioutil.WriteFile` to write the buffer to a file. Instead of doing this, it should `os.Open` the file and call the template's `Execute` function to write the contents directly to the file (which is an implementation of `io.Writer`. This is a minor optimization.

Should probably be done after https://github.com/deis/builder/pull/316, as doing it beforehand would result in some conflicts.

### PR DESCRIPTION
**Pull request by arschles**
# Summary of Changes

Instead of creating the pre-receive hook script and writing the results to an intermediate `*bytes.Buffer`, this change writes the script's results directly to an `*os.File`.

# Issue(s) that this PR Closes

Fixes #321 

# Associated [End To End Test](https://github.com/deis/workflow-e2e) PR(s)

None. This path only changes an implementation detail.

# Associated [Documentation](https://github.com/deis/workflow) PR(s)

None. This path only changes an implementation detail.

# Associated [Design Document](http://docs.deis.io/en/latest/contributing/design-documents)(s)

None. This path only changes an implementation detail.

# Testing Instructions

1. Create a Deis Cluster
2. Register an app with `deis create`
3. Add your SSH key with `deis keys:add`
4. `git push deis master` from your Buildpack or Dockerfile app (for example, [example-go](https://github.com/deis/example-go))

The application should be successfully deployed.

# Pull Request Hygiene TODOs

Please make sure the below checklist is complete.

- [x] Your pull request is concise and to the point (make another PR for refactoring nearby code)
- [x] Your commits follow the [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)

### CODE REVIEW

**Comment by bacongobbler** [comment]
is this punt-able to v2.2 or does this need to go in for this release? I'm assuming it's punt-able since it's an enhancement but just wanna make sure. :)

**Comment by arschles** [comment]
This is puntable to 2.2. Moving

**Comment by bacongobbler** [comment]
LGTM, but needs to pass CI and get a rebase before merging :)

**Comment by arschles** [comment]
@bacongobbler thanks for the bump. I had forgot about this trying to get a successful CI run, and then it went out of date. I may end up closing as this is far from a required item for 2.2. Stay tuned.

**Pull request merged**
