### PR TITLE
chore(Dockerfile): Refactor image to use ubuntu-slim

### PR DESCRIPTION
**Pull request by krancour**

### CODE REVIEW

**Comment by arschles** [comment]
@krancour this LGTM. has it been tested in the wild, or does it need to be?

**Comment by krancour** [comment]
@arschles it should run through the normal CI process.

**Comment by arschles** [comment]
@krancour sounds good. any special corners that should be covered here, that CI may not cover?

**Comment by krancour** [comment]
Not that I can think of.

**Comment by arschles** [comment]
code LGTM, pending the jenkins CI run succeeding

**Pull request merged**
