### PR TITLE
fix(gitreceive/storage/bucket.go): silence bucket creation errors

### LINKED ISSUE #109: silence bucket create errors
In the current master, the second `git push` and beyond prints this error:

```console
remote: mc: <ERROR> Unable to make bucket 'http://10.3.0.231:9000/git'. The requested bucket name is not available.
```

The error is ignored by the git receive hook and the deploy is successful, but it shouldn't be printed... #106 should fix the error by replacing the entire usage of `mc`. This issue is for fixing until that happens.

### PR DESCRIPTION
**Pull request by arschles**
Fixes #109

### CODE REVIEW

**Comment by aledbf** [comment]
LGTM

**Comment by bacongobbler** [comment]
Checked [upstream](https://github.com/aws/aws-sdk-go/blob/c09f1bb2f2270137bd1708d4668dc6beb2fb52f2/models/apis/s3/2006-03-01/api-2.json#L66-L71) to ensure this was the correct error code. This seems to check out. LGTM!

**Comment by arschles** [comment]
Thanks @bacongobbler - I just wish they included a constant for it

**Comment by bacongobbler** [comment]
The problems with auto-generated SDKs is that they're not very programmable :'(

**Comment by arschles** [comment]
heh, true

**Pull request merged**
