### PR TITLE
fix(makefile): make the docker-build call the build

### LINKED ISSUE #285: intermittent ssh exchange identifcation failure
# Summary

CI has seen failures relating to ssh when deploying an app via `git push`.

## Description

The failure looks like:
```
16:52:12 ------------------------------
16:52:12 Apps with a deployed app 
16:52:12   can't create an existing app
16:52:12   /go/src/github.com/deis/workflow-e2e/tests/apps_test.go:135
16:52:13 $ deis login http://deis.10.99.253.8.nip.io --username=test-81 --password=asdf1234
16:52:13 Logged in as test-81
16:52:13 $ deis apps:create test-174487287 
16:52:14 Creating Application... ...done, created test-174487287
16:52:14 Git remote deis added
16:52:14 remote available at ssh://git@deis.10.99.253.8.nip.io:2222/test-174487287.git
16:52:14 $ GIT_SSH=/tmp/deis-workflow-home629812519/.ssh/git-ssh git push deis master
16:52:24 
ssh_exchange_identification: Connection closed by remote host
16:52:24 fatal: Could not read from remote repository.
16:52:24 
16:52:24 Please make sure you have the correct access rights
16:52:24 and the repository exists.
16:52:24 $ deis apps:destroy --app= --confirm=
16:52:24  !    WARNING: Potentially Destructive Action
16:52:24  !    This command will destroy the application: test-174487287
16:52:24  !    To proceed, type "test-174487287" or re-run this command with --confirm=test-174487287
16:52:24 
16:52:24 > Error: App test-174487287 does not match confirm , aborting.
16:52:24 
16:52:24 • Failure in Spec Setup (BeforeEach) [11.841 seconds]
16:52:24 Apps
16:52:24 /go/src/github.com/deis/workflow-e2e/tests/apps_test.go:204
16:52:24   with a deployed app
16:52:24   /go/src/github.com/deis/workflow-e2e/tests/apps_test.go:174
16:52:24     can't create an existing app [BeforeEach]
16:52:24     /go/src/github.com/deis/workflow-e2e/tests/apps_test.go:135
16:52:24 
16:52:24     No future change is possible.  Bailing out early after 10.016s.
16:52:24     Got stuck at:
16:52:24         ssh_exchange_identification: Connection closed by remote host
16:52:24         fatal: Could not read from remote repository.
16:52:24         
16:52:24         Please make sure you have the correct access rights
16:52:24         and the repository exists.
16:52:24         
16:52:24     Waiting for:
16:52:24         Done, test-174487287:v\d deployed to Deis
16:52:24 
16:52:24     /go/src/github.com/deis/workflow-e2e/tests/tests_suite_test.go:362
16:52:24 ------------------------------
```

This is taken from [workflow-test-pr build 258](https://ci.deis.io/job/workflow-test-pr/258/console) and logs from this run can be seen [here](https://ci.deis.io/job/workflow-test-pr/258/artifact/logs/258/)

Another example job exists [here](https://ci.deis.io/job/workflow-test-pr/251/)

### Replication Steps

This error is intermittent but has by runs of the [`workflow-test-pr`](https://ci.deis.io/job/workflow-test-pr) job

cc @smothiki @kmala

### PR DESCRIPTION
**Pull request by kmala**
# Summary of Changes

make docker-build call build
Jenkis use a common script to build an image out of the PR and run e2e tests https://github.com/deis/jenkins-jobs/blob/master/jobs/component_jobs.groovy#L101-L113
# Issue(s) that this PR Closes

fixes #285 

# Testing Instructions

Please provide a detailed list for how to test the changes in this PR.

1. Do make docker-build docker-push 
2. Use the above image deploy deis cluster
3. deploy an app and it should work fine

# Pull Request Hygiene TODOs

- [x] Your pull request is concise and to the point (make another PR for refactoring nearby code)
- [x] Your commits are squashed into logical units of work
- [x] Your commits follow the [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)

### CODE REVIEW

**Comment by arschles** [comment]
Why doesn't the existing deploy script, which runs `make build docker-build ...` already work? It seems like something else is wrong here.

**Comment by vdice** [comment]
@arschles I can't remember why the divergence with `_scripts/deploy.sh` occurred.  Remember, while that script does get run by Travis on merges to master, it doesn't or PRs (Travis won't push images from forked repo due to https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests).

**Comment by arschles** [comment]
@vdice So if the goal here is to get new builder images for PRs, I'd rather not make the fix in the `Makefile`, because adding `build` as a dependency of `docker-build` will change the standard dev workflow. Can we make Jenkins just run `make build docker-build`?

**Comment by vdice** [comment]
@arschles I see.  Yes, we could do that; we'd just have to ensure all component repos tracked by Jenkins (https://github.com/deis/jenkins-jobs/blob/master/common.groovy#L1-L15) have a `build` task (would be surprising if they didn't but just a double-check)

**Comment by kmala** [comment]
@arschles I see other places https://github.com/deis/router/blob/master/Makefile#L49 and https://github.com/deis/registry/blob/master/Makefile#L41 where we build a binary doing the same.So which method do you think is the better one...so that all the components can be on the same plate

**Comment by arschles** [comment]
I'd also be ok with adding a new build target, possibly called `docker-build-complete`...

**Comment by arschles** [comment]
@kmala Good point. However, since we don't seem to have a standard across all repos, I strongly prefer that we don't change this repo until we do settle on a standard.

**Pull request merged**
