### PR TITLE
fix(slugbuilder-cache): fix typo in comments

### PR DESCRIPTION
**Pull request by aboyett**
a minor typo fix: sotrage -> storage

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by jeroenvisser101** [comment]
LGTM!

**Comment by Joshua-Anderson** [comment]
Jenkins, add to whitelist

**Comment by jeroenvisser101** [comment]
Weird, jenkins is throwing errors, seem unrelated to a comment change?

**Comment by Joshua-Anderson** [comment]
@jeroenvisser101 I restarted CI. It's a little flakey and some of our test k8s cluster have been having  ETCD issues.

**Pull request merged**
