### PR TITLE
chore(Dockerfile): bump git to v2.8.4

### LINKED ISSUE #362: upgrade git to 2.8+
cross-posting from deis/deis#5031

```
><> kd exec deis-builder-mmsdf -- git --version
git version 2.7.4
```

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #362 
closes deis/deis#5031

### CODE REVIEW

**Comment by bacongobbler** [comment]
closing/re-opening to bump jenkins

**Comment by helgi** [comment]
2.9 is out

**Comment by bacongobbler** [comment]
let's bump it once we audit 2.9. For now this fixes some critical issues and I have not seen any upgrade problems from 2.7 to 2.8 :)

**Comment by krancour** [comment]
If I am not mistaken, newer versions of git are usually available from git's own ppa. Installing from there would spare us from building from source and from all the cleanup that must necessarily follow that to keep images small.

**Comment by bacongobbler** [comment]
> If I am not mistaken, newer versions of git are usually available from git's own ppa. Installing from there would spare us from building from source and from all the cleanup that must necessarily follow that to keep images small.

Do you feel that's something we need to do in this PR or just a passing comment? :)

**Comment by mboersma** [comment]
> newer versions of git are usually available from git's own ppa

It would be cleaner and safer IMHO to use the official package, agreed. I'm ok with building from source, but if there is time to refactor this PR I think @krancour has a good point.

**Comment by bacongobbler** [comment]
let's refactor later and just get v2.8.4 out the door so we can close this security loophole. I'll file a ticket to reafactor how we build git

**Pull request merged**
