### PR TITLE
ref(pkg/gitreceive/*,pkg/hooks): add and use a controller hooks client (WIP)

### LINKED ISSUE #82: create a client for the Deis controller
#72 introduces some duplicated code to talk with the Deis controller. This issue is for refactoring all of it into a common controller client. Create a new `github.com/deis/builder/pkg/controller` package and put the client in there

### PR DESCRIPTION
**Pull request by arschles**
Fixes #82 

Needs manual testing.

### CODE REVIEW

**Comment by aledbf** [comment]
@arschles which version of `deis/workflow` is required to test this?
Using current workflow mater I see this error:
```
remote: [ERROR] running git receive hook [Deis controller endpoint http://10.3.2.71:80/v2/hooks/push: expected status code 201, got 404]
```

**Comment by bacongobbler** [comment]
We're all running off the `deis-dev` chart on a bare kubernetes cluster for development:

```
curl -s https://get.helm.sh | bash
helm repo add deis https://github.com/deis/deis
helm fetch deis/deis-dev
helm generate deis-dev
helm install deis-dev
```

**Comment by arschles** [comment]
Removing the `v2-beta1` milestone since this is not critical for the beta release

**Comment by arschles** [comment]
This patch has fallen way behind HEAD, and the rebase required to bring it up to date is extremely complex, as much of the code herein has been removed, heavily refactored, or moved. Since we have working code now, I'm electing to close this but leave #82 open

**Pull request closed without merging**
